### ISSUE TITLE
[BUG]Omnic fluid doesn't allow electric boilers to make mining fluids

### ISSUE THREAD

**Issue by TokMor** [OmnissiahZelos/omnimatter#256]
**Describe the bug**
Electric boilers do not have sluid omnic acid to liquid omnic acid for mining

**To Reproduce**
1. Place an electric boiler and view recipes

**Expected behavior**
The recipe for turning sluids to fluids should appear in electric boilers for mining fluids

**Screenshots**
regular boiler
![image](https://user-images.githubusercontent.com/28193512/90943863-c4641580-e3e9-11ea-968a-d10b3f4e8e62.png)
electric boiler
![image](https://user-images.githubusercontent.com/28193512/90943871-cf1eaa80-e3e9-11ea-8af3-f3a4e1043bf8.png)
![image](https://user-images.githubusercontent.com/28193512/90943876-d5148b80-e3e9-11ea-886d-6817715cb065.png)

**Additional context**
For the forge

**Additional Info**
- Factorio Version: 1.0
- Minimal required mods to reproduce: https://www.dropbox.com/sh/a6lwkzvq6fqafg0/AABg-cumUefE1A1-C1uaYXdPa?dl=0
- Savegame: https://www.dropbox.com/s/55pkym8qzu5bsp8/Omni%20Forge%202020%20Q3.zip?dl=0

**Comment by Pezzawinkle** [comment]
This looks like the wrong entity of which you are referring... angels electric boiler is different to the omnifluid converter boiler (even if they look the same *may add a tint in the new version*).
If memory serves, the mining fluid recipes have been added to at least one of the active versions, not sure if that has been fixed since this report was made... I am not prioritizing omnifluid fixes at the moment, but am keeping an eye on them for the rework im chipping away at.
