### ISSUE TITLE
[Angels ovehaul TECH] Cycle in technology

### ISSUE THREAD

**Issue by Klestch653** [OmnissiahZelos/omnimatter#321]
I don't understand much about the device of mods, so I'll just throw off what I think will help to help with the solution.
This error occurs when I enable OmniEnergy. My build also includes bob's and angel's mods. Thank you in advance for your help.
![image](https://user-images.githubusercontent.com/64656680/107246592-d42fee80-6a49-11eb-9510-9dee0099474e.png)
[factorio-current.log](https://github.com/OmnissiahZelos/omnimatter/files/5944967/factorio-current.log)

**Comment by SqFKYo** [comment]
Please use the provided template:
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Additional Info**
- Factorio Version: 0.xx.xx
- Minimal required mods to reproduce:
- Savegame:

**Comment by Pezzawinkle** [comment]
`tech-specialised-labs-basic`
refers to angles tech overhaul, which is currently not supported by omnimods at this point, its on the to-do list though.

**Comment by Cereal-Sam** [comment]
Exactly, not supported by omni at the moment.
This issue got semi fixed with the last update, we hide and force angels tech overhaul setting to false now to avoid confusion.
