### ISSUE TITLE
[Omnifluid] [Feature] Some ideas about mod (let's make best replacement of weak fluid mechanics)

### ISSUE THREAD

**Issue by lictw** [OmnissiahZelos/omnimatter#324]
At mod portal you write about UPS, but i think more about current implementation of pipes in factorio. Try to compare this with mechanic of conveyors.. It's incomparable! 

I can't filter fluids (one input pipe with many filtered output), can't merge/split liquids, connections of pipes are bulky and ugly (imho), pressures in pipes are unpredictable. All about fluids are about pain. I like pretty setups, like something complex and useful, some time ago i tried to build stations to accept and provide multiply fluids with LTN mod and it's really pure pain!

**Proposals**
1. Don't kill vanilla mechanics completely! Don't disable fluids, don't make several items unnecessary (pumps, fluid wagons, etc). Let's situational choise instead.
2. Add 1x1 structure that connects as pipe on one side and has manipulator on other (longer/filtered version, logic). It will accept fluid and output "liquid item" (barrel). Of course it must rotating, we will use it to pass fluids in assemblers for crafting. But need additional research couse of internal buffers (ex. don't take new barrel if assemblers can't fully accept it, take another instead), it will be good if i could pass two fluids via single loader. So don't need to replace vanilla recipes, better add rounded that consumes whole barrel as alternatives.
3. Reduce stack size (360 is very high value), but better make this configurable. Configurable of fluid count in one barrel good idea too, but it may be hard/destructive for recipes rounding.
4. Wather is resource, it must has water source, don't make it from air.
5. Remove current custom structures. We don't need alternative recipes in boilers, we decide at the exit what exactly it will be. Vanilla structures are simple and elegant.

**Comment by lictw** [comment]
As additional advantage such changes makes mod less global, we could enable it at any time without break anything.

**Comment by Pezzawinkle** [comment]
As someone who is in the middle of re-writing omnifluid, and someone who has dealt with low UPS bases in the past.
1) omnifluid is situational in its exclusion of fluids for power generation (temperature versioned steam in the generators, mining fluids and flamethrower turret (at least in the new unfinished version)).
2) additional "assemblers" or furnace type entities would defeat the purpose of removing fluids for assemblers, to the point that it would be worse than just leaving fluids.
3) This is planned to be configurable in the updated version when I push that. 360 may seem high, but is a reasonable value for things like an angel-bobs game. The rounding/balancing around recipes is done mathematically and keeps the existing ratio regardless of that setting value, and this feature is planned on being implemented to the re-write shortly.
4) This is NOT specific to omnifluid, but I do plan on investigating the offshore pump(s) in the rework as I am not a fan of the place everywhere mechanic. (no promises)
5) NO! The concept of the boilers is to allow the conversion of sluids to fluids, specifically for boilers\miners\fluid-turrets. The original version of this mod (back in the 0.15/0.16 days) removed all fluids which caused issues with power generation since steam had to be transferred to the steam engines.
5a) FYI those "simple and elegant" vanilla structures are indeed simple, but it is very hard to get a furnace type entity for solid-in-fluid-out and visa vera to work in a UPS friendly manner. I can look into making the sluids-boiler into that type before i push, but i do not think that is overly-wise.

If you wish to see the progress of the re-write (its slow i know), please take a look at the branch:
https://github.com/OmnissiahZelos/omnimatter/tree/omnifluid-draft-re-write

**Comment by Pezzawinkle** [comment]
> As additional advantage such changes makes mod less global, we could enable it at any time without break anything.

This is far from simple, doing a change in this way that affects recipes and structures cannot simply be turned on and off without a game restart, it should not do much "breaking" when adding or removing the mod. As in the map will load, but you may have to do some redecorating, as is required with all overhaul mods.

**Comment by lictw** [comment]
Seems like the liquid itself is problem for UPS, i thought only in pipes. So my main proposal about "liquid" inserters doesn't solve the problem, without last other things don't have sense. Seems i just want something another and it isn't related to this mod. So it can be closed, i will try to find another way to make this.
